### ISSUE TITLE
struct-copy fails accross modules

### ISSUE THREAD

**Issue by bdeket** [racket/typed-racket#930] opened 2020-04-29 09:08 UTC
### What version of Racket are you using?
7.7.0.2
### What program did you run?
```
#lang typed/racket/base

(module mod1 typed/racket/base
  (provide (all-defined-out))
  (struct a ([aa : Number]) #:type-name A)
  (define a1 (a 1))
  (struct-copy a a1 [aa 2]))

(module mod2 typed/racket/base
  (require (submod ".." mod1))
  (define a2 (a 1))
  (struct-copy a a2 [aa 2]))
```
### What should have happened?
create new struct a

### If you got an error message, please include it here.
struct-copy: accessor name not associated with the given structure type in: a-aa

probably related to #322

**Comment by bdeket** [comment] 2020-05-01 18:23
more problems with #:type-name:
```
#lang racket/base

(module mod1 typed/racket/base
  (provide (all-defined-out))
  (struct a ([bb : Number]) #:type-name A))

(module mod2 racket/base
  (require racket/match)
  (require (submod ".." mod1))
  (match (a 1)
    [(a b) b]))
```
fails with the cryptic error: 
match: syntax error in pattern in: (a b)

**Comment by bdeket** [comment] 2020-11-17 10:17
update:
at the moment [(master e0a372d)](https://github.com/racket/typed-racket/tree/e0a372d1052bc9fa2c12a759577d4b936b285102)

* The first part type-checks as expected.
* The second part type-checks if the second module is also typed/racket/base or if the #:type-name is dropped. But the same error remains between typed and untyped code.

However if the first part is changed to:
```
#lang typed/racket/base

(module mod1 typed/racket/base
  (provide (all-defined-out))
  (struct a ([aa : Number]) #:type-name A)
  (define a1 (a 1))
  (struct-copy a a1 [aa 2]))

(module mod2 racket/base
  (require (submod ".." mod1))
  (define a2 (a 1))
  (struct-copy a a2 [aa 2]))
```
The error is `struct-copy: identifier is not bound to a structure type in: a`

So introducing a #:type-name breaks using struct-copy or match across the typed boundary

**Comment by default-kramer** [comment] 2021-03-31 02:21
It may be worth noting that the #:type-name works in `struct-copy` and `match` across the typed boundary. For example, this works

```
#lang typed/racket/base

(module mod1 typed/racket/base
  (provide (all-defined-out))
  (struct a ([aa : Number]) #:type-name A)
  (define a1 (a 1))
  (struct-copy a a1 [aa 2]))

(module mod2 racket/base
  (require (submod ".." mod1))
  (define a2 (a 1))
  (struct-copy A a2 [aa 2]))
```

**Comment by bdeket** [comment] 2021-03-31 06:06
nice, thank you for pointing that out.
But is counterintuitive that in typed and untyped you have to do the opposite:
```
#lang racket/base

(module mod1 typed/racket/base
  (require racket/match)
  (provide (all-defined-out))
  (struct a ([aa : Number]) #:type-name A)
  (define a1 (a 1))
  
  (struct-copy a a1 [aa 2]);works
  ;(struct-copy A a1 [aa 2]);fails
  
  (match (a 1) [(a b) b]);works
  ;(match (a 1) [(A b) b]);fails
  )

(require 'mod1)
(require racket/match)
(define a2 (a 1))

;(struct-copy a a1 [aa 2]);fails
(struct-copy A a1 [aa 3]);works

;(match a1 [(a b) b]);fails
(match a1 [(A b) b]);works
```
If this is the intention, this issue can be closed. And maybe it can be added to the documentation.

**Comment by capfredf** [comment] 2021-04-05 21:51
Thanks for the report. This is definitely a bug. Type names is never intended to use in place of struct names

**Comment by default-kramer** [comment] 2021-04-05 22:17
@capfredf It sure is handy though. Oftentimes in untyped Racket I will write code like this

```
(define (change-something foo)
  (struct-copy foo foo [something "something else"]))
```

and then be sad because now `foo` is no longer bound to the struct id. I have to rename the argument to avoid the clash, or set up an alias for the struct id. I'm currently using aliases so that I can do `(struct-copy foo* foo ...)`. So if Typed Racket keeps the current behavior, I'll enjoy it.

Also, when I saw this, I wondered if I introduced this bug here https://github.com/racket/typed-racket/issues/506. I don't think so... but if I did, I'll blame the lack of a test that should have stopped me :)

**Comment by capfredf** [comment] 2021-04-06 00:33
No, #506 has nothing to do with this issue. TR should export its type name, struct name, and constructor name from a struct's definition, though all three names can be identical. Previously TR didn't handle this well. #1050 has partially solved this problem.  And I am working on a fix for this issue.

**Comment by samth** [comment] 2021-04-06 19:21
@default-kramer do you have code that will break if #1067 changes the type name not to work in `struct-copy`? Or is this just something you think is nice in the abstract?

**Comment by default-kramer** [comment] 2021-04-06 19:51
@samth More just a "nice in the abstract" observation. I do have a small amount of code that will break but it won't be any trouble to update.

**Comment by samth** [comment] 2021-04-06 19:56
@default-kramer Is that new code since 8.0? Or would that break something that worked in 8.0?

**Comment by default-kramer** [comment] 2021-04-06 19:59
@samth Hmm, I'm not sure. I upgraded from an official 7.x build to an 8.x nightly build. I can't remember when I first wrote the code, but I can check (later tonight) whether the official 8.0 build allows type names as struct names if that would help.

**Comment by samth** [comment] 2021-04-06 20:00
That would be great. I want to make sure we preserve compatibility with what shipped in previous releases, but the snapshot state recently is a less important compatibility goal.

**Comment by default-kramer** [comment] 2021-04-07 02:46
@samth I just confirmed the behavior exists in Racket 8.0 [cs]. Specifically, when #:type-name is present, untyped code can use the type name in `struct-copy` and `match`, while the struct id does not work. (If you stay within Typed Racket, both the struct id and the type name work.)

**Comment by capfredf** [comment] 2021-04-07 14:02
Ah, I misled @samth yesterday. A type name specified by `#:type-name` has been allowed to be used in the place where a struct name is expected maybe since 2015 when the feature was introduced. 

I will keep the compatibility in my fix

**Closed** 2021-04-09 20:53 UTC
