### ISSUE TITLE
TR: casting makes type checking unsound for mutable boxes/vectors/structs

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#108] opened 2015-04-09 23:52 UTC
###### Originally submitted on: Fri Jan 30 21:20:01 -0500 2015

I'm not familiar with this problem. Let me guess the right fix: when we cast (Boxof A) to (Boxof B), should we wrap around it a contract ensuring anything going into the box as type A, (in addition to ensuring anything going out of the box has type B, which TR already does)?

##### Steps to Reproduce:

The following 3 expressions all produce "hi" typechecked as Integer:

```racket
(begin
  (define b1 : (Boxof Integer) (box 42))
  (define b2 (cast b1 (Boxof String)))
  (set-box! b2 "hi")
  (unbox b1))

(begin
  (define v1 : (Vectorof Integer) (vector 42))
  (define v2 (cast v1 (Vectorof String)))
  (vector-set! v2 0 "hi")
  (vector-ref v1 0))

(begin
  (struct (X) s ([i : X]) #:mutable)
  (define s1 : (s Integer) (s 42))
  (define s2 (cast s1 (s String)))
  (set-s-i! s2 "hi")
  (s-i s1))
```

##### Release:

```
6.1.1.7--2015-01-17(2b8acb3/a)
```

##### Environment:

```
unix "Linux ubuthink 3.16.0-28-generic #38-Ubuntu SMP Fri Dec 12 17:37:40 UTC 2014 x86_64
 x86_64 x86_64 GNU/Linux" (x86_64-linux/3m) (get-display-depth) = 32
Human Language: english
(current-memory-use) 333255660
raco pkg (show):
Installation-wide:
 Package            Checksum     Source
 main-distribution  b660f028...  catalog main-distribution
 racket-lib         e93899ff...  catalog racket-lib
 [185 auto-installed packages not shown]
User-specific for installation "snapshot":
 Package        Checksum              Source
 rmacs          4bef6487...           catalog...acs/master
 soft-contract                        link...soft-contract
 [1 auto-installed package not shown]



Collections:
("/home/pcn/.racket/snapshot/collects"
 (non-existent-path))
("/home/pcn/bin/Racket/collects"
 (".gitignore" "acks" "compiler" "data" "db" "dynext" "ffi" "file" "info" "info-domain"
 "json" "launcher" "net" "openssl" "pkg" "planet" "racket" "rackunit" "raco" "reader"
 "realm" "s-exp" "scheme" "setup" "srfi" "syntax" "unstable" "version" "xml"))

Recent Internal Errors: 
Computer Language: (("Determine language from source") (#(#t print mixed-fraction-e #f #t
 debug) (default) #() "#lang racket\n" #t #t ((test) (main)) #t))
```

**Comment by takikawa** [comment] 2015-04-09 23:52
###### On Fri, 30 Jan 2015 21:28:19 -0500, asumu at ccs dot neu dot edu wrote:


On 2015-01-30 21:20:02 -0500, pcn@cs.umd.edu wrote:
> A new problem report is waiting at
>   http://bugs.racket-lang.org/query/?cmd=view&pr=14955
> Reported by Phil Nguyen for release: 6.1.1.7--2015-01-17(2b8acb3/a)
> *** Description:
> I'm not familiar with this problem. Let me guess the right fix: when
> we cast (Boxof A) to (Boxof B), should we wrap around it a contract
> ensuring anything going into the box as type A, (in addition to
> ensuring anything going out of the box has type B, which TR already
> does)?

Yes, I think this might be the same as this bug (and I think the
proposed fix there is the same as your fix, though not yet implemented):

  http://bugs.racket-lang.org/query/?cmd=view&audit-trail&database=default&pr=13626

Coincidentally, we just discussed this bug on IRC last night. So I don't
forget, it might be useful to discuss a potential solution here.

The implementation of the fix is potentially tricky because we need to
apply a contract corresponding to the type of the expression, which we
don't know when the `cast` macro expands.

To solve this, we could attach a syntax property to the casted
expression (`b1` in your first example) that marks it as a casted
expression (the property might store an identifier corresponding to a
contract definition we will generate later).

In the new pass, the entire module or top-level expression is traversed
and when an expression with the property is found, its type is looked up
in the type table and put in some table.

The contract generation pass would then consult the table to generate
contracts for casts.

Cheers,
Asumu

**Comment by takikawa** [comment] 2015-04-09 23:52
###### On Fri, 30 Jan 2015 21:35:32 -0500, asumu at ccs dot neu dot edu wrote:


On 2015-01-30 21:28:19 -0500, Asumu Takikawa wrote:

I think that while revising this e-mail I deleted an important sentence
or two. I meant to say earlier that the fix might require the
introduction of a new pass that goes between typechecking and contract
generation.  This pass looks at the syntax properties that are applied
by the `cast` macro as I described.

Cheers,
Asumu

**Comment by takikawa** [comment] 2015-04-09 23:52
###### On Sat, 31 Jan 2015 18:21:04 -0500, asumu classified this bug as duplicate

Duplicate of PR 13626

**Comment by AlexKnauth** [comment] 2016-05-25 22:23
This loophole can be closed by having `cast` generate two contracts. The first would be an `Any` contract as if it was going from typed to untyped, and the second would be the contract for the type it's casting to, as if it was going from untyped to typed.

That's what this does:
https://github.com/AlexKnauth/typed-racket/commit/4696144d46a18c688a55974685632f50e10beec3

The error message for the original "How-To-Repeat" example from [PR 13626](http://bugs.racket-lang.org/query/?cmd=view&pr=13626) is this:
```
. . ../../Applications/Racket/2016-05-23/tr/Racket v6.5.0.5/collects/racket/contract/private/blame.rkt:159:0: #<procedure:f>: contract violation
  Attempted to use a higher-order value passed as `Any` in untyped code: #<procedure:f>
  in: Any
  contract from: typed-world
  blaming: cast
   (assuming the contract is correct)
  at: unsaved-editor:13.1
```

However, it throws that same error if you try to use it in a safe way:
```
#lang typed/racket

(: v Boolean)
(define v #f)
(: f (Boolean -> Boolean))
(define (f x)
  (set! v x)
  x)

;; Should be perfectly safe, but errors anyway.
((cast f (Boolean -> Boolean)) #t)
```

To do this properly, `cast` would have to somehow tell the type-checking pass to get the existing type of the original expression, and then the type-checking pass would have to give that type to the contract-generation pass to both that contract and the one for the new type.

But I'm stuck, because the `cast` macro needs to generate the code for the contract checks before the type-checking pass happens.

Anyone have any ideas?

**Comment by takikawa** [comment] 2016-05-25 22:35
Can you just have the `cast` macro generate two sets of contract definitions as we discussed in the lab? That is, one contract definition is the one that checks the original expression's type. The second is the usual contract definition. You can supply a payload that's some non-type value (like `'cast`) to indicate that it's for the cast, and handle it appropriately.

Then the main problem is getting the typechecking pass to communicate the type information. An extra free id table keyed on the contract identifier should work for this, assuming you keep that identifier around. Getting at the actual type is the tricky part though, I think, but if you can grab the expanded syntax object for the original value expression you can look it up in the type-table.

**Comment by AlexKnauth** [comment] 2016-05-26 00:28
My too-restrictive commit (https://github.com/AlexKnauth/typed-racket/commit/4696144d46a18c688a55974685632f50e10beec3) does generate two sets of contracts, but the one that's supposed to check the original expression's type generates a contract for `Any` instead (which is more restrictive because it doesn't allow uses of higher-order values). 

You mentioned using putting some kind of sentinel value there instead of using `(syntax-local-lift-expression (make-contract-def-rhs/from-typed #'Any #f #f))`. I could do that by generating an identifier, putting that identifier in the expansion, and then defining that identifier later, but that would result in an unbound identifier error when it finishes expanding, because the type-checking and contract generation both happen after it finishes expanding. 

I guess I could define a different version of `contract-def-property` (which `make-contract-def-rhs/from-typed` uses), and that could do something ...

**Closed** 2016-06-06 19:27 UTC
