### ISSUE TITLE
Regression in type-checking elements of `in-naturals` sequence

### ISSUE THREAD

**Issue by philnguyen** [racket/typed-racket#579] opened 2017-07-11 15:03 UTC
### What version of Racket are you using?
v6.10.0.1

### What program did you run?

```racket
#lang typed/racket

(for/list : (Listof Natural) ([s '(foo bar)]
                              [i : Natural (in-naturals)])
  i)
```

### What should have happened?
Program type-checks as in `v6.9.0.4`

### If you got an error message, please include it here.
```
; Type Checker: type mismatch
;   expected: Nonnegative-Integer
;   given: Integer
;   in: (for/list : (Listof Natural) ((s (quote (foo bar))) (i : Natural (in-naturals))) i)
```

**Comment by stchang** [comment] 2017-07-11 16:54
I think Racketscript is affected by this as well (using `range`)
https://travis-ci.org/vishesh/racketscript/jobs/251352200 

```
raco setup: error: during making for <pkgs>/racketscript-compiler/racketscript/compiler
  racketscript-compiler/racketscript/compiler/transform.rkt:577:7: Type Checker: type mismatch
    expected: StatementKey
    given: Integer
    in: (for/list ((i : Natural (range (length args))) (arg : Symbol args)) (ILVarDec arg (ILApp (ILRef result-id (quote getAt)) (list (ILValue i)))))
compiling: <pkgs>/racketscript-compiler/racketscript/compiler/transform.rkt
```

**Comment by pnwamk** [comment] 2017-07-11 21:05
It looks like it's related to the recent change in Racket's for/list expansion: https://github.com/racket/racket/commit/51bf69e3562bdbc45184eabe1722da135431ea43

That change is more or less reverting for/list expansion to the way it previously worked.

It appears this code also does not type check in Racket <= 6.7 (i.e. it appears to only type check with the now reverted for/list expansion):

```racket
#lang typed/racket

(for/list : (Listof Natural) ([s '(foo bar)]
                              [i : Natural (in-naturals)])
  i)
```

As for Racketscript, that's probably a combination of this for/list expansion change and the fact that `range` is now expanded differently when used in for loops (see https://github.com/racket/racket/commit/597661fa4e90475843318d052859aedabbcff9f7). So it worked previously (i.e. Racket 6.7 and before), then
1. for loop expansion was changed (December 2016)
2. range expansion was changed (January 2017) and it continued to type check because of (1)
3. for loop expansion was reverted to the old behavior (21 days ago)
4. Now the expansion of range in Racketscript, which was changed by (2), no longer type checks because the change from (1) was removed by (3).

Anyway, I think that's accurate. It doesn't say anything about how to fix it though (sorry)!

**Comment by samth** [comment] 2017-07-11 21:08
Does using `in-range` instead of `range` fix the problem in Racketscript?

**Comment by samth** [comment] 2017-07-11 21:08
cc @stamourv and @rfindler for release regression/backwards compatibility issues

**Comment by stchang** [comment] 2017-07-11 21:15
cc @vishesh

**Comment by pnwamk** [comment] 2017-07-11 21:16
@samth off the top of my head... I was under the impression the January 2017 change w.r.t. `range`'s expansion in for loops made `in-range` and `range` expand the same, so I would expect them to be type checked identically.

**Comment by stamourv** [comment] 2017-07-12 01:21
@samth: Noted. WIll add as a blocker once I instantiate the checklist.

**Comment by samth** [comment] 2017-07-12 01:32
I didn't necessarily intend for this to be a blocker, especially since I
don't think it will be fixed before the release. Just wanted the release
managers to be aware.

**Comment by vishesh** [comment] 2017-07-12 06:10
@samth Using `in-range` produces same error. 

On side node, unrelated to this issue, type `StatementKey` in the error (in Stephen's message) is not in the namespace of the module we are currently compiling. It is defined in another module `il-analyze.rkt` but is not exported by it. Shouldn't it print the expected type that is in the namespace of the module?

**Comment by samth** [comment] 2017-07-13 15:42
The type printing issue is a long-standing issue with Typed Racket and global state -- it's indeed a problem, but not related to this bug.

**Comment by rfindler** [comment] 2017-07-13 15:58
I think that it makes sense to have some special cases in the implementation of #lang typed/racket that identifies places where the racket expansion has changed that breaks typechecking for programs that type checked before, and then to think through just how bad of a hack would be required to make existing examples continue to typecheck. That is, don't have typed/racket's `for/list` just be racket's, but instead have it do some extra checking on the syntax to fix up things so that we don't break old programs.

(And just to clarify, I think it makes sense to think though this and see how bad it looks and weigh that against the pain we are asking the users to cope with, perhaps even in consultation with those whose code is affected (if we can communicate with them). I'm not saying it is mandatory to actually make such a change.)

**Comment by samth** [comment] 2017-07-13 16:14
@rfindler The obvious way to do that is to change typed/racket's `for/list` to be the version in 6.8 and 6.9, but that has the problems that led @mflatt to revert the changes. I'm looking at the expansion now and maybe there's a hack we can come up with that's less bad than that.

**Comment by rfindler** [comment] 2017-07-13 16:17
Oh, I agree that seems unwise. But can you not add a special-case "type rule" to `for/list` that covers a subset of what the other expansion allows, but big enough that the programs that we've found type check (and perhaps some small generalization of them)? I'm not sure what it would expand into, but in the worst case, it could just expand into something that says "I already know this type is correct, nothing to see here, move along, dear typechecker".

**Comment by samth** [comment] 2017-07-13 16:22
After looking at this quickly, I think a hack to special-case `alt-reverse` somehow will work.

**Comment by samth** [comment] 2017-07-13 21:05
I've made some progress here; the following now type checks:

```
(for/list : (Listof Integer) ([s '(foo bar)]
                              [i : Integer (in-naturals)])
  i)
```

Is that enough to fix Racketscript?

**Comment by samth** [comment] 2017-07-14 23:04
This program demonstrates the problem:

```racket
#lang typed/racket

((letrec-values (((for-loop)
                    (lambda (fold-var pos)
                      #;
                      (let ((i : Natural pos))
                            (for-loop (cons i fold-var) (+ pos '1)))
                      (if #t
                          (let ((i : Natural pos))
                            (for-loop (cons i fold-var) (+ pos '1)))
                          fold-var))))
     for-loop)
   null
   0)
```

I think the problem is in `find-annotation`, but I'm just recording my thoughts for the moment.

**Comment by samth** [comment] 2017-07-16 23:55
I now have a PR that fixes the reported issue. Hopefully this fixes Racketscript as well.

**Closed** 2017-07-17 00:09 UTC

**Comment by rfindler** [comment] 2017-07-17 00:14
sweet!

**Comment by samth** [comment] 2017-07-17 00:16
Racketscript installs successfully.

**Comment by vishesh** [comment] 2017-07-18 07:05
Awesome! Thanks for checking with RacketScript.
