### ISSUE TITLE
Annotating a rest argument on a function with an optional argument is unsound

### ISSUE THREAD

**Issue by lexi-lambda** [racket/typed-racket#1192] opened 2022-02-15 17:17 UTC
This program is patently incorrect and should be rejected:

```racket
#lang typed/racket

(define (bad [opt #f] . [vs : (Vectorof Any) *]) : Any
  (vector-ref vs 0))

(bad)
```

However, it is not:

```
$ racket bad.rkt
invalid memory reference.  Some debugging context lost
  context...:
   body of "/tmp/bad.rkt"
```

The bug is in the type assigned to `vs` in the body of `bad`. It should have type `(Listof (Vectorof Any))`, since it’s a rest argument, but in fact it is assigned just `(Vectorof Any)`. This is wildly unsound.

**Comment by capfredf** [comment] 2022-02-17 02:22
duplicate of #862

**Closed by capfredf** 2022-02-17 02:22 UTC
