### ISSUE TITLE
Constructors in `typed/web-server/http` not provided

### ISSUE THREAD

**Issue by t0mpr1c3** [racket/typed-racket#1346] opened 2023-11-07 23:26 UTC
### What version of Racket are you using?
8.10

### What program did you run?
```
(require typed/web-server/http)
(binding:form #"" #"")
(make-binding:form #"" #"")
```

### What should have happened?
```
(binding:form #"" #"")
```

### If you got an error message, please include it here.
```
binding:form: unbound identifier in: binding:form
make-binding:form: unbound identifier in: make-binding:form
```

**Comment by LiberalArtist** [comment] 2024-07-31 01:25
I think this is an example of https://github.com/racket/typed-racket/issues/1366

**Comment by t0mpr1c3** [comment] 2024-07-31 11:03
I agree

**Comment by jbclements** [comment] 2024-08-03 20:52
Since 1346 < 1366, can I close #1366 as a duplicate of this one?

**Comment by t0mpr1c3** [comment] 2024-08-03 21:02
No, close #1346 because #1366 is a more general issue.

**Closed** 2024-08-03 21:15 UTC
